/* Generated by Together */

/**
 * For a description of Permanent visitors, follow hyperlink to the Administration use case for issuing a new Permanent visitor permit.
 * @url element://model:project::PACSUS/design:node:::diykfgkuaa1f5ob1r92
 */
public class Permanent_visitor_permit extends Permit {
}


