import java.util.Observer;

import javax.swing.JFrame;

/* Generated by Together */

/**
 * This class represents the interactive interface to PACSUS administration functions carried out in the Estates and Campus Services Office.  Information about these functions is in the Administration use case diagram (hyperlinked from this class).
 * The interface comprises one screen with all the functions present on it: they could all be on view at once, or perhaps in alternative JPanels (in a JFrame with JTabbedPane); the current date (day number) is always displayed.
 * There could be any number of instances of this class, potentially one for each workstation in the office, with different staff carrying different functions.
 * The class implements Observer, and observes the system status so that it can keep the displayed current date correct.
 * @stereotype boundary
 * @url element://model:project::PACSUS/design:node:::dbdq3gkua8d3p-nqwlsp
 * @url element://model:project::PACSUS/design:view:::gyozhgkty8w6ujdkjwo
 * @url element://model:project::PACSUS/design:node:::fog6ngkua8d3f-rwvbrf
 * @url element://model:project::PACSUS/design:node:::fog6ngkua8d3f-rwvbrf
 * @url element://model:project::PACSUS/design:node:::3id5ngkua54su-jdp9dt
 * @url element://model:project::PACSUS/design:node:::3id5ngkua54su-jdp9dt
 * @url element://model:project::PACSUS/design:view:::d8yvlgktya8js5ls11m
 * @url element://model:project::PACSUS/design:node:::dbdq3gkua8d3p-nqwlsp
 */
public class Administration_office extends JFrame implements Observer {
    /**
     * Each instance of Administration_office has a navigable association to the permit list so that it can enquire about/add/delete/modify permits.
     * @supplierCardinality 1
     * @clientCardinality 1..*
     * @label Administration functions
     * @directed
     */
    private Permit_list lnkPermit_list;

    /**
     * Each instance of Administration_office has a navigable association to the vehicle list so that it can enquire about/add/delete/modify vehicle details.
     * @clientCardinality 1..*
     * @supplierCardinality 1
     * @label Administration functions
     * @directed
     */
    private Vehicle_list lnkVehicle_list;

    /**
     * Each instance of Administration_office has a navigable association to the system status so that it can find out status information about the system.
     * @clientCardinality 1..*
     * @supplierCardinality 1
     * @label See date
     * @directed
     */
    private System_status lnkSystem_status;
}
